import type { ComponentType } from "svelte";

export type Language =
    | "Afrikaans"
    | "Albanian"
    | "Arabic"
    | "Armenian"
    | "Azerbaijani"
    | "Basque"
    | "Belarusian"
    | "Bengali"
    | "Bosnian"
    | "Bulgarian"
    | "Catalan"
    | "Cebuano"
    | "Chinese (Simplified)"
    | "Chinese (Traditional)"
    | "Croatian"
    | "Czech"
    | "Danish"
    | "Dutch"
    | "English (UK)"
    | "English (US)"
    | "English (Australian)"
    | "English (Canadian)"
    | "English (Indian)"
    | "English (Irish)"
    | "English (New Zealand)"
    | "English (Scottish)"
    | "English (South African)"
    | "Esperanto"
    | "Estonian"
    | "Filipino"
    | "Finnish"
    | "French"
    | "French (Canadian)"
    | "French (Belgian)"
    | "French (Swiss)"
    | "Galician"
    | "Georgian"
    | "German"
    | "German (Austrian)"
    | "German (Swiss)"
    | "Greek"
    | "Gujarati"
    | "Haitian Creole"
    | "Hausa"
    | "Hebrew"
    | "Hindi"
    | "Hmong"
    | "Hungarian"
    | "Icelandic"
    | "Igbo"
    | "Indonesian"
    | "Irish"
    | "Italian"
    | "Italian (Swiss)"
    | "Japanese"
    | "Javanese"
    | "Kannada"
    | "Kazakh"
    | "Khmer"
    | "Korean"
    | "Lao"
    | "Latin"
    | "Latvian"
    | "Lithuanian"
    | "Macedonian"
    | "Malay"
    | "Malayalam"
    | "Maltese"
    | "Maori"
    | "Marathi"
    | "Mongolian"
    | "Nepali"
    | "Norwegian"
    | "Persian"
    | "Polish"
    | "Portuguese"
    | "Portuguese (Brazilian)"
    | "Portuguese (European)"
    | "Punjabi"
    | "Romanian"
    | "Russian"
    | "Serbian"
    | "Slovak"
    | "Slovenian"
    | "Somali"
    | "Spanish"
    | "Spanish (Latin American)"
    | "Spanish (European)"
    | "Swahili"
    | "Swedish"
    | "Tamil"
    | "Telugu"
    | "Thai"
    | "Turkish"
    | "Ukrainian"
    | "Urdu"
    | "Uzbek"
    | "Vietnamese"
    | "Welsh"
    | "Yiddish"
    | "Yoruba"
    | "Zulu";

export type NativeLanguage = Language;

export type ProficiencyLevel = "Beginner" | "Intermediate" | "Advanced";

export type Message = {
    role: "user" | "assistant";
    content: string;
}; 